name: Build & Tests

on:
  push:
    branches: [ main, workflows ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Run Tests
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore src
    - name: Build
      run: dotnet build src --configuration Release
    - name: Unit Tests
      run: dotnet test tests.unit
    - name: Integration Tests
      run: dotnet test tests.integration
